name: LiveWeather
main: com.liveweather.Initiator
api: ["1.0.14"]
version: "1.7"
author: Werwolf2303

permissions:
  liveweather.commands:
    description: "Allows the user to run the commands of the LiveWeather plugin"
    default: false