on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clone Repository
        run: git clone -b ${GITHUB_REF##*/} https://github.com/werwolf2303/LiveWeather-Nukkit
      - name: Build with Maven
        run: mvn --batch-mode -f LiveWeather-Nukkit/pom.xml --update-snapshots package
      - name: upload to nightly
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: /home/runner/work/LiveWeather-Nukkit/LiveWeather-Nukkit/LiveWeather-Nukkit/target/LiveWeather-Nukkit.jar
         asset_name: LiveWeather-Nukkit.jar
         asset_content_type: application/jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Build
          path: /home/runner/work/LiveWeather-Nukkit/LiveWeather-Nukkit/LiveWeather-Nukkit/target/LiveWeather-Nukkit.jar
